# Generated by Django 4.0.6 on 2022-07-05 21:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0002_remove_post_author_post_name_of_user_comments'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Comments',
            new_name='Comment',
        ),
    ]
