# Generated by Django 4.0.6 on 2022-07-08 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0005_alter_post_username_alter_profile_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='name_of_user',
            field=models.CharField(default='?', max_length=50),
        ),
    ]
