# Generated by Django 4.0.6 on 2022-07-08 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0006_alter_post_name_of_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='username',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='username',
        ),
        migrations.AlterField(
            model_name='post',
            name='name_of_user',
            field=models.CharField(default='1', max_length=50),
        ),
    ]
