# Generated by Django 4.0.6 on 2022-07-08 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0008_profile_username'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='username',
            new_name='testing',
        ),
    ]
