# Generated by Django 4.0.6 on 2022-07-09 20:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0013_alter_post_name_of_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='profile',
            old_name='testing',
            new_name='user_from_model',
        ),
        migrations.AlterField(
            model_name='comment',
            name='post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='linkoapp.post'),
        ),
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.ForeignKey(default='User Name', on_delete=django.db.models.deletion.CASCADE, to='linkoapp.profile'),
        ),
    ]
