# Generated by Django 4.0.6 on 2022-07-13 17:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkoapp', '0016_alter_profile_options_alter_profile_user_from_model'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='user_from_model',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
