# Generated by Django 4.0.6 on 2022-07-13 20:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkoapp', '0018_alter_profile_options_remove_profile_user_from_model_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='is_retired',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='photo_url',
        ),
        migrations.RemoveField(
            model_name='profile',
            name='previous_companies',
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
