# Generated by Django 4.0.6 on 2022-07-14 00:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkoapp', '0026_alter_portrait_user_alter_post_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portrait',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
