# Generated by Django 4.0.6 on 2022-07-14 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0028_alter_comment_post'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='first_name',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
