# Generated by Django 4.0.6 on 2022-07-14 21:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('linkoapp', '0030_portrait_email_portrait_last_name_portrait_photo_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='portrait',
            name='previous_companies',
            field=models.TextField(null=True),
        ),
        migrations.AlterField(
            model_name='portrait',
            name='user',
            field=models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL),
        ),
    ]
