# Generated by Django 4.0.6 on 2022-07-15 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0034_alter_portrait_previous_companies'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='username',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='portrait', to='linkoapp.portrait'),
        ),
    ]
