# Generated by Django 4.0.6 on 2022-07-18 00:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0037_alter_bucketlist_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucketlist',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='linkoapp.portrait'),
        ),
    ]
