# Generated by Django 4.0.6 on 2022-07-18 01:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0038_alter_bucketlist_user'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucketlist',
            old_name='user',
            new_name='userP',
        ),
    ]
