# Generated by Django 4.0.6 on 2022-07-18 01:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0039_rename_user_bucketlist_userp'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='userP',
        ),
        migrations.AddField(
            model_name='bucketlist',
            name='userFk',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='linkoapp.portrait'),
        ),
    ]
