# Generated by Django 4.0.6 on 2022-07-18 01:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0040_remove_bucketlist_userp_bucketlist_userfk'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucketlist',
            name='userFk',
        ),
    ]
