# Generated by Django 4.0.6 on 2022-07-18 01:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0043_bucket_delete_bucketlist'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bucket',
            name='complete',
        ),
        migrations.RemoveField(
            model_name='bucket',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='bucket',
            name='userP',
        ),
    ]
