# Generated by Django 4.0.6 on 2022-07-18 02:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0044_remove_bucket_complete_remove_bucket_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bucket',
            name='complete',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='bucket',
            name='created_date',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='bucket',
            name='userP',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='linkoapp.portrait'),
        ),
    ]
