# Generated by Django 4.0.6 on 2022-07-19 15:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0045_bucket_complete_bucket_created_date_bucket_userp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bucket',
            name='userP',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='linkoapp.portrait'),
        ),
    ]
