# Generated by Django 4.0.6 on 2022-07-19 15:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0046_alter_bucket_userp'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bucket',
            old_name='userP',
            new_name='userB',
        ),
    ]
