# Generated by Django 4.0.6 on 2022-07-19 15:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0047_rename_userp_bucket_userb'),
    ]

    operations = [
        migrations.CreateModel(
            name='Buckets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('complete', models.BooleanField(default=False)),
                ('created_date', models.DateTimeField(auto_now=True)),
                ('userB', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='linkoapp.portrait')),
            ],
        ),
        migrations.DeleteModel(
            name='Bucket',
        ),
    ]
