# Generated by Django 4.0.6 on 2022-07-19 16:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('linkoapp', '0048_buckets_delete_bucket'),
    ]

    operations = [
        migrations.AlterField(
            model_name='buckets',
            name='userB',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='linkoapp.portrait'),
        ),
    ]
